apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    uid: loki
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000

  - name: Tempo
    type: tempo
    access: proxy
    url: http://localhost:3200
    uid: tempo
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -1h
        spanEndTimeShift: 1h
        filterByTraceID: true
        filterBySpanID: false
        tags:
          - key: service.name
            value: service_name
      nodeGraph:
        enabled: false

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    uid: prometheus
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      customQueryParameters: ""
      timeInterval: 15s

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://localhost:4040
    uid: pyroscope
    isDefault: false
    editable: true
