version: '3.8'

services:
  # BeTrace Backend API
  betrace-backend:
    image: betrace-backend:latest
    container_name: betrace-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
      - PYROSCOPE_APPLICATION_NAME=betrace-backend
    networks:
      - betrace-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Grafana with BeTrace plugin
  grafana:
    image: betrace-grafana-plugin:latest
    container_name: betrace-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=betrace-app
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana-data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    networks:
      - betrace-net
    depends_on:
      - tempo
      - loki
      - prometheus

  # Grafana Tempo (trace storage)
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"   # HTTP
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    networks:
      - betrace-net

  # Grafana Loki (log aggregation)
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    networks:
      - betrace-net

  # Prometheus (metrics)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - betrace-net

  # Grafana Pyroscope (continuous profiling)
  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope
    ports:
      - "4040:4040"
    volumes:
      - pyroscope-data:/var/lib/pyroscope
    networks:
      - betrace-net

networks:
  betrace-net:
    driver: bridge

volumes:
  grafana-data:
  tempo-data:
  loki-data:
  prometheus-data:
  pyroscope-data:
