version: "0.5"

processes:
  loki:
    command: nix run ./.flox/pkgs#loki-wrapped
    working_dir: /Users/sscoble/Projects/betrace
    availability:
      restart: on_failure
      max_restarts: 3
    readiness_probe:
      http_get:
        host: localhost
        port: 3100
        path: /ready
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 3

  tempo:
    command: nix run ./.flox/pkgs#tempo-wrapped
    working_dir: /Users/sscoble/Projects/betrace
    availability:
      restart: on_failure
      max_restarts: 3
    readiness_probe:
      http_get:
        host: localhost
        port: 3200
        path: /ready
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 3

  prometheus:
    command: nix run ./.flox/pkgs#prometheus-wrapped
    working_dir: /Users/sscoble/Projects/betrace
    availability:
      restart: on_failure
      max_restarts: 3
    readiness_probe:
      http_get:
        host: localhost
        port: 9090
        path: /-/ready
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 3

  pyroscope:
    command: nix run ./.flox/pkgs#pyroscope-wrapped
    working_dir: /Users/sscoble/Projects/betrace
    availability:
      restart: on_failure
      max_restarts: 3
    readiness_probe:
      http_get:
        host: localhost
        port: 4040
        path: /healthz
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 3

  alloy:
    command: nix run ./.flox/pkgs#alloy-wrapped
    working_dir: /Users/sscoble/Projects/betrace
    depends_on:
      loki:
        condition: process_healthy
      tempo:
        condition: process_healthy
    availability:
      restart: on_failure
      max_restarts: 3

  grafana:
    command: nix run ./.flox/pkgs#grafana-wrapped
    working_dir: /Users/sscoble/Projects/betrace
    depends_on:
      loki:
        condition: process_healthy
      tempo:
        condition: process_healthy
      prometheus:
        condition: process_healthy
    availability:
      restart: on_failure
      max_restarts: 3
    readiness_probe:
      http_get:
        host: localhost
        port: 12015
        path: /api/health
      initial_delay_seconds: 3
      period_seconds: 5
      timeout_seconds: 3

  backend:
    command: |
      cd backend && \
      export CGO_ENABLED=1 && \
      export GOFLAGS="-mod=vendor" && \
      go run ./cmd/betrace-backend
    working_dir: /Users/sscoble/Projects/betrace
    availability:
      restart: on_failure
      max_restarts: 3
    readiness_probe:
      http_get:
        host: localhost
        port: 8080
        path: /health
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 3
