version: '3.8'

services:
  # Grafana Tempo for distributed tracing
  tempo:
    image: grafana/tempo:latest
    container_name: fluo-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"   # Tempo query frontend
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    networks:
      - fluo-observability

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: fluo-prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - fluo-observability

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: fluo-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    depends_on:
      - tempo
      - prometheus
    networks:
      - fluo-observability

  # Optional: Jaeger for additional trace viewing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: fluo-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # gRPC
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - fluo-observability

  # Optional: OTEL Collector for advanced routing
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: fluo-otel-collector
    command: [ "--config=/etc/otel-collector.yaml" ]
    ports:
      - "4319:4317"   # OTLP gRPC (alternative port)
      - "4320:4318"   # OTLP HTTP (alternative port)
      - "8888:8888"   # Prometheus metrics
      - "13133:13133" # Health check
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    depends_on:
      - tempo
      - prometheus
      - jaeger
    networks:
      - fluo-observability

volumes:
  tempo-data:
  prometheus-data:
  grafana-data:

networks:
  fluo-observability:
    driver: bridge