---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: betrace

---
# ConfigMap for BeTrace configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: betrace-config
  namespace: betrace
data:
  BETRACE_PORT_BACKEND: "12011"
  BETRACE_PORT_GRPC: "12012"
  BETRACE_DATA_DIR: "/data"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo:4317"
  OTEL_SERVICE_NAME: "betrace-backend"

---
# Secret for signature key
apiVersion: v1
kind: Secret
metadata:
  name: betrace-secret
  namespace: betrace
type: Opaque
stringData:
  BETRACE_SIGNATURE_KEY: "change-me-in-production"

---
# PersistentVolumeClaim for rule storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: betrace-data
  namespace: betrace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: betrace-backend
  namespace: betrace
  labels:
    app: betrace-backend
    version: "2.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: betrace-backend
  template:
    metadata:
      labels:
        app: betrace-backend
        version: "2.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "12011"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: betrace/backend:2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 12011
          protocol: TCP
        - name: grpc
          containerPort: 12012
          protocol: TCP
        env:
        - name: BETRACE_PORT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: betrace-config
              key: BETRACE_PORT_BACKEND
        - name: BETRACE_PORT_GRPC
          valueFrom:
            configMapKeyRef:
              name: betrace-config
              key: BETRACE_PORT_GRPC
        - name: BETRACE_DATA_DIR
          valueFrom:
            configMapKeyRef:
              name: betrace-config
              key: BETRACE_DATA_DIR
        - name: BETRACE_SIGNATURE_KEY
          valueFrom:
            secretKeyRef:
              name: betrace-secret
              key: BETRACE_SIGNATURE_KEY
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: betrace-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: betrace-config
              key: OTEL_SERVICE_NAME
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /v1/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v1/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: betrace-data

---
# Service - HTTP REST API
apiVersion: v1
kind: Service
metadata:
  name: betrace-backend
  namespace: betrace
  labels:
    app: betrace-backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 12011
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 12012
    targetPort: grpc
    protocol: TCP
  selector:
    app: betrace-backend

---
# Service - LoadBalancer (optional, for external access)
apiVersion: v1
kind: Service
metadata:
  name: betrace-backend-external
  namespace: betrace
  labels:
    app: betrace-backend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 443
    targetPort: grpc
    protocol: TCP
  selector:
    app: betrace-backend

---
# HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: betrace-backend-hpa
  namespace: betrace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: betrace-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max

---
# PodDisruptionBudget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: betrace-backend-pdb
  namespace: betrace
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: betrace-backend

---
# NetworkPolicy (optional, for network isolation)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: betrace-backend-netpol
  namespace: betrace
spec:
  podSelector:
    matchLabels:
      app: betrace-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: grafana
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 12011
    - protocol: TCP
      port: 12012
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: tempo
    ports:
    - protocol: TCP
      port: 4317
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
      endPort: 53
