{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "betrace.fullname" . }}-grafana-secret
  labels:
    {{- include "betrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
stringData:
  admin-password: {{ .Values.grafana.config.security.admin_password | quote }}
{{- end }}
