{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "betrace.fullname" . }}-grafana
  labels:
    {{- include "betrace.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      {{- include "betrace.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/grafana-configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "betrace.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "betrace.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.grafana.plugin.enabled }}
      initContainers:
        - name: copy-betrace-plugin
          image: "{{ .Values.grafana.plugin.image.repository }}:{{ .Values.grafana.plugin.image.tag }}"
          command: ["sh", "-c", "cp -r /plugin /grafana-plugins/betrace-app"]
          volumeMounts:
            - name: plugins
              mountPath: /grafana-plugins
      {{- end }}
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.grafana.service.targetPort }}
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.config.security.admin_user | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "betrace.fullname" . }}-grafana-secret
                  key: admin-password
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: {{ .Values.grafana.config.auth.anonymous.enabled | quote }}
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: {{ .Values.grafana.config.auth.anonymous.org_role | quote }}
            - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
              value: {{ .Values.grafana.config.plugins.allow_loading_unsigned_plugins | quote }}
            - name: GF_PATHS_PLUGINS
              value: "/var/lib/grafana/plugins"
            - name: GF_PATHS_PROVISIONING
              value: "/etc/grafana/provisioning"
          volumeMounts:
            - name: plugins
              mountPath: /var/lib/grafana/plugins
            - name: provisioning
              mountPath: /etc/grafana/provisioning
            {{- if .Values.grafana.persistence.enabled }}
            - name: storage
              mountPath: /var/lib/grafana
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
      volumes:
        - name: plugins
          emptyDir: {}
        - name: provisioning
          configMap:
            name: {{ include "betrace.fullname" . }}-grafana-provisioning
        {{- if .Values.grafana.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "betrace.fullname" . }}-grafana-pvc
        {{- end }}
      {{- with .Values.grafana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
