global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: fluo-backend
    static_configs:
      - targets:
          - localhost:12011
        labels:
          service: fluo-backend
    metrics_path: /metrics

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
